title: Tanks Game
description: A game based on the old WORM games but instead uses tanks. The game was made in 3 months by 2 students in computer science and mathematics. All artworks were made by Cedrik Dubois. All physics and mathematics implementation was done by William Adam-Grenier
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
